### ISSUE TITLE
issue with entry files on windows

### ISSUE THREAD

**Issue by richardklotz** [robdonn/storybook-module-federation#1]
https://github.com/robdonn/storybook-module-federation/blob/f495f6421277f53f308cd2710d1d62d553c11c02/src/main.ts#L45

![image](https://user-images.githubusercontent.com/8438634/132361897-7468574e-6475-4e72-b08b-2c304df869b5.png)

Possible solution is to escape the backslash?

Something like:

```
entryFile.replace(/\\/g, '\\\\')
```

**Comment by robdonn** [comment]
Thanks @richardklotz for finding this, I'll upload the fix ASAP.

**Comment by robdonn** [comment]
Version `0.6.0` has been released which should work for you now on windows. Tested locally on a Windows 10 machine.
