### ISSUE TITLE
TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by paschini** [robdonn/storybook-module-federation#2]
Hello o/ 

I'm trying to "module federationize" my Storybook. it uses Style9, which works normally, but I need a webpackFinal object in my config. If I remove that object from the storyBookConfig constant, the storybook app compiles, and the app importing the components is able to find them. But since Style9 is not compiling anything, nothing works. If i keep my webpackFinal object, then the storyapp doesn't compile, and I get this error:

`ERR! TypeError: Cannot read property 'map' of undefined
ERR!     at Object.webpackFinal (/Users/camila.paschini/Developer/Platform-Phoenix-UI/node_modules/storybook-module-federation/dist/main.js:46:26)
`

Here's the constants i'm using:
````
const storybookConfig = {
  core: {
    builder: 'webpack5',
  },
  stories: [
    "../src/main/javascript/**/*.stories.mdx",
    "../src/main/javascript/**/*.stories.@(js|jsx|ts|tsx)"
  ],
  addons: ["@storybook/addon-links", "@storybook/addon-essentials"],

  webpackFinal: async config => {
    config.resolve.modules = [
      ...(config.resolve.modules || []),
      path.resolve(__dirname, "../src/main/javascript"),
      "node_modules"
    ];

    config.module.rules.push({
      test: /\.tsx?$/,
      use: Style9Plugin.loader
    });

    config.plugins.push(new Style9Plugin());

    return config;
  }
};

const moduleFederationConfig = {
  name: "phoenixUI",
  filename: "remoteEntry.tsx",
  exposes: {
    "./Components/Button": path.resolve(
      __dirname,
      "../src/main/javascript/Button.tsx"
    )
  }
};

````
Style9 is a CSS compiler plugin. The config for Style9 works. As in, if i remove module federation from my .storybook/main.js, it works. I am using Storybook version 6.3.12 though, have not tried downgrading it.

Thx in advance!

**Comment by kirill-konshin** [comment]
`webpackFinal` could return a promise. That's exactly your case. Remove `async` and it will work.

But `storybook-module-federation` should check return type of `webpackFinal` internally, so it's still a bug.

**Comment by LongLiveCHIEF** [comment]
Can confirm removing `async` worked for me in very similar scenario.

**Comment by LongLiveCHIEF** [comment]
Also @robdonn , I saw your work on PR to merge this functionality into storybook, and can't thank you enough.

**Comment by robdonn** [comment]
Hey @paschini, sorry for the unforgivably slow response to this issue. Version `0.6.2` has now been published which supports providing an async function to `webpackFinal`.

**Comment by Harikumar-Rajendran** [comment]
Hi,

I am trying to expose the entire storybook, so that it can be imported in to Cockpit app. From the example I could see exporting a component(button) from story book works fine, similarly is it possible to export the storybook as a whole app?
